#! /bin/sh

bspc monitor -d free free2 shell browser music chat
bspc config border_width        1
bspc config focused_border_color \#7fa2ac
# bspc config normal_border_color \#deeaff
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

# Autostart

picom --experimental-backend &
$HOME/.config/polybar/launch.sh &

pkill sxhkd
sxhkd &

pkill dunst
dunst -conf ~/dotfiles/config/dunst/dunstrc &

feh --bg-fill ~/dotfiles/wallpapers/girlsnow.jpg
